apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: cp-kafka-3:7.8.0-corretto21
          env:
            - name: CLUSTER_ID
              value: '4LHe29W0QYqCBbKKcgr7PA'

            # KRaft configuration
            - name: KAFKA_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_NODE_ID
              value: '0'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '0@kafka-srv:9093'

            # Listener configuration
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'

            - name: KAFKA_LISTENERS
              value: >
                INTERNAL://0.0.0.0:9092,
                EXTERNAL://0.0.0.0:9094,
                CONTROLLER://0.0.0.0:9093

            - name: KAFKA_ADVERTISED_LISTENERS
              value: >
                INTERNAL://kafka-srv:9092,
                EXTERNAL://localhost:9094

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'INTERNAL'

            # Single-node safe defaults
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'

          ports:
            - name: internal
              containerPort: 9092
            - name: external
              containerPort: 9094
            - name: controller
              containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
